---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  
  
  
namespace: "localstack"
namePrefix: "localstack-"
images:
  - name: "localstack/localstack"
    newTag: "4.0.3"
  
  
configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
  
